/**************************************************************************************************************
 * altobeam iot at cmd file 
 *
 * Copyright (c) 2018, altobeam.inc   All rights reserved.
 * Permission is hereby granted for use on Altobeam IOT 6421 only,
 * in which case ,it is free to  redistribute it and/or modify
 *
*****************************************************************************************************************/

#ifndef _FLASH_CONFIG_PARAM_H_
#define _FLASH_CONFIG_PARAM_H_

#include "atbm_general.h"

//#include "flash.h"
#define DEVICE_SECTOR_SIZE 0x001000u
#define DEVICE_PAGE_SIZE   0x000100u

#if (CHIP_TYPE==CHIP_ATHENAB)
#define FLASH_BASE 0x12000000
#else
#define FLASH_BASE 0x400000
#endif

#define FLASH_SIZE FLASH_2M
//#include "app_flash_param_2M.h"
#define FLASH_CODE_UPDATA_FLAG_SECTION_LEN	DEVICE_PAGE_SIZE
#define FLASH_BOOT_CODE_SECTION_ADDR 		(FLASH_BASE+0x000000)  /*struct flash_boot_section*/

#define FLASH_CONST_USER_PARAM_SECTION_ADDR 	(FLASH_BASE+0x00E000)  /*struct flash_ap_config_section*/
#define FLASH_BOOT_PARAM_SECTION_ADDR 		(FLASH_BASE+0x00F000)  /*struct flash_ap_config_section*/

#define FLASH_CODE_SECTION_ADDR 			(FLASH_BASE+0x010000)   
#define FLASH_CODE_CONFIG_SECTION_ADDR 		(FLASH_BASE+0x0FFC00) 
#define FLASH_CODE_CONFIG_SECTION_LEN 		0x300  
#define FLASH_CODE1_SECTION_ADDR 			FLASH_CODE_SECTION_ADDR  
#define FLASH_CODE_SECTION_LEN 				(FLASH_CODE_CONFIG_SECTION_ADDR-FLASH_CODE_SECTION_ADDR)  
#define FLASH_CODE2_SECTION_ADDR 			(FLASH_BASE+0x040000) 
#define FLASH_CODE1_SECTION_LEN 			(FLASH_CODE2_SECTION_ADDR-FLASH_CODE1_SECTION_ADDR) 
#define FLASH_CODE2_SECTION_LEN 			(FLASH_BOOT_PARAM_SECTION2_ADDR -FLASH_CODE2_SECTION_ADDR -FLASH_CODE_UPDATA_FLAG_SECTION_LEN)  
#define FLASH_CODE_FLAG_SECTION_ADDR		(FLASH_BASE+0x0FFF00)  /* UPDATE FLAG*/
#define FLASH_BOOT_PARAM_SECTION2_ADDR		(FLASH_BASE+0x100000)  /*struct flash_ap_config_section*/
#define FLASH_USR_KEY_SECTION_ADDR			(FLASH_BASE+0x101000)  /*user key*/
#define FLASH_USR_KEY_SECTION_LEN			(0x1000)  /*user key len*/
#define FLASH_BOOT_PARAM_SECTION2_BAK_ADDR	(FLASH_BASE+0x102000)  /*boot param backup*/
#define FLASH_BOOT_PARAM_SECTION2_BAK_LEN	(0x1000)  /*boot param backup len*/
#define FLASH_USR_DATA_SECTION_ADDR 		(FLASH_BASE+0x103000)  /*user data1*/
#define FLASH_USR_DATA_SECTION_LEN          (0x8000)
#define FLASH_USR_DATA_SECTION2_ADDR		(FLASH_BASE+0x10B000)  /*user data2*/
#define FLASH_USR_DATA_SECTION2_LEN         (0x3000)
#define FLASH_DEBUG_EVENT_INDEX 			(FLASH_USR_DATA_SECTION2_ADDR)
#define FLASH_DEBUG_EVENT_INFO_1 			(FLASH_USR_DATA_SECTION2_ADDR + 0x1000)
#define FLASH_DEBUG_EVENT_INFO_2 			(FLASH_USR_DATA_SECTION2_ADDR + 0x2000)
#define FLASH_DELTA_GAIN_TEMP_DCXO_ADDR  	(FLASH_BASE + 0x10E000)
#define FLASH_REBOOT_USER_FLAG_ADDR			(FLASH_BASE+0x10F000)  /*reboot user flag */
#define FLASH_REBOOT_USER_FLAG_LEN          (0x1000)
#if CONFIG_OTA_COMPRESS_BIN
	#define FLASH_USR_DATA_SECTION3_ADDR		(FLASH_BASE+0x110000)  /*user data2*/
	#define FLASH_USR_DATA_SECTION3_LEN         (0x50000)
	#define FLASH_CODE1_UPDATA_SECTION_ADDR		(FLASH_BASE+0x160000)  /* FLASH_CODE1*/
	#define FLASH_CODE1_UPDATA_SECTION_LEN		(0xA0000 - FLASH_CODE_UPDATA_FLAG_SECTION_LEN) /* FLASH_CODE1*/
	#define FLASH_CODE2_UPDATA_SECTION_ADDR		(FLASH_CODE1_UPDATA_SECTION_ADDR + FLASH_CODE1_UPDATA_SECTION_LEN)  /* FLASH_CODE2*/
	#define FLASH_CODE2_UPDATA_SECTION_LEN		(0)  /* FLASH_CODE2*/
#else
	#define FLASH_CODE1_UPDATA_SECTION_ADDR		(FLASH_BASE+0x110000)  /* FLASH_CODE1*/
	#define FLASH_CODE1_UPDATA_SECTION_LEN		FLASH_CODE1_SECTION_LEN  /* FLASH_CODE1*/
	#define FLASH_CODE2_UPDATA_SECTION_ADDR		(FLASH_CODE1_UPDATA_SECTION_ADDR + FLASH_CODE1_UPDATA_SECTION_LEN)  /* FLASH_CODE2*/
	#define FLASH_CODE2_UPDATA_SECTION_LEN		(FLASH_CODE2_SECTION_LEN)  /* FLASH_CODE2*/
#endif

#define FLASH_CODE_UPDATA_FLAG_SECTION_ADDR	(FLASH_CODE2_UPDATA_SECTION_ADDR + FLASH_CODE2_UPDATA_SECTION_LEN)  /* UPDATE FLAG*/

#define FLASH_CODE2_UPDATA_SECTION_END_ADDR      FLASH_CODE_UPDATA_FLAG_SECTION_ADDR

#define BLOCK_BOOT_PARAM_ADDR 			FLASH_BOOT_PARAM_SECTION_ADDR 
#define BLOCK_BOOT_PARAM_LEN 			0x400


#if (CHIP_TYPE == CHIP_ATHENAB)
#define FLASH_OFFSET_MASK               0xffffff
#else
#define FLASH_OFFSET_MASK               0x3fffff //FLASH_BASE-1
#endif //


#define BLOCK_UART_PARAM_ADDR (FLASH_BOOT_PARAM_SECTION_ADDR + BLOCK_BOOT_PARAM_LEN)
#define BLOCK_UART_PARAM_LEN 0x100

#define BLOCK_TCP_PARAM_ADDR (BLOCK_UART_PARAM_ADDR + BLOCK_UART_PARAM_LEN)
#define BLOCK_TCP_PARAM_LEN  0x100

#endif /*_FLASH_CONFIG_PARAM_H*/
